# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'verbose'
ESlogging:
    enabled: true
    label: MQTT2MELCLOUD
    loglevel: info
    options:
        indexPrefix: logs
        clientOpts:
            node: http://es.elastic.home
mqtt:
    # URL to MQTT broker
    url: 'mqtt://127.0.0.1'
    # Configuration passed to the MQTT library
    options:
        username: 'mqtt_username'
        password: 'mqtt_password'
    # Prefix to mqtt topic
    topicPrefix: 'melcloud'

melcloud: 
  username: ''
  password: ''
  interval: 300000     # time between device status updates
  refresh: 600000      # time between building+device updates
